FROM docker.io/apache/iceberg-rest-fixture:1.8.1

USER root

# Add Postgres JDBC driver
RUN curl -L -o /usr/lib/iceberg-rest/postgresql-42.7.5.jar https://repo1.maven.org/maven2/org/postgresql/postgresql/42.7.5/postgresql-42.7.5.jar
USER iceberg:iceberg

CMD ["java", "-cp", "postgresql-42.7.5.jar:iceberg-rest-adapter.jar", "org.apache.iceberg.rest.RESTCatalogServer"]
