services:
  rest-catalog:
    image: localhost/apache/iceberg-rest-fixture:1.8.1
    build:
      context: .
      dockerfile: Dockerfile.catalog
    container_name: rest-catalog
    networks:
      - breweries-net
    ports:
      - 8181:8181
    environment:
      - AWS_ACCESS_KEY_ID=minio
      - AWS_SECRET_ACCESS_KEY=${BREWERIES_PASSWORD:?}
      - AWS_REGION=us-east-1

      - CATALOG_URI=jdbc:postgresql://brewery-postgres:5432/catalog
      - CATALOG_JDBC_USER=postgres
      - CATALOG_JDBC_PASSWORD=${BREWERIES_PASSWORD:?}

      - CATALOG_WAREHOUSE=s3://${SPARK_WAREHOUSE_BUCKET:?}/
      - CATALOG_IO__IMPL=org.apache.iceberg.aws.s3.S3FileIO
      - CATALOG_S3_ENDPOINT=http://minio:9000

    deploy:
      resources:
        limits:
          cpus: 0.5
          memory: 200M

    depends_on:
      minio-init:
        condition: service_completed_successfully
      brewery-postgres:
        condition: service_healthy

  spark:
    image: localhost/spark:latest
    build:
      context: .
      dockerfile: Dockerfile
    container_name: spark
    hostname: spark
    networks:
      - breweries-net
    ports:
      - 7077:7077
      - 8080:8080

    volumes:
      - ./entrypoint.sh:/opt/spark/bin/entrypoint.sh:ro
      - ./conf/spark-defaults.conf:/opt/spark/conf/spark-defaults.conf:rw
    environment:
      - REST_CATALOG_ENDPOINT=http://rest-catalog:8181
      - AWS_ENDPOINT=http://minio:9000
      - AWS_ACCESS_KEY_ID=${SPARK_WAREHOUSE_BUCKET:?}
      - AWS_SECRET_ACCESS_KEY=minio
      - AWS_DEFAULT_BUCKET=${BREWERIES_PASSWORD:?}
      - MARQUEZ_API_ENDPOINT=http://marquez-api:5000

    deploy:
      resources:
        limits:
          cpus: 2
          memory: 2G

    depends_on:
      minio-init:
        condition: service_completed_successfully
      rest-catalog:
        condition: service_started
      marquez-api:
        condition: service_healthy
